name: Python application

on:
  workflow_dispatch:
    branches: [ main ]
    

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: joeapo108/stan:v2.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: check local dir
        uses: ./
    
      - name: list dir
        run : |
              ls -la
              pwd
        
      - name: run script
        run : ./run.py

#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install flake8 pytest
#         pip install pandas
#         pip install requests
#         pip install psycopg2
#         pip install sqlalchemy
#         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#     - name: Run Script

#       run: python run.py
         
         
